ENV      := /usr/bin/env
CC       := cc
OPT      :=  
#OPT      := -Ofast -flto
UNUSED   :=  -DLOWHAT_ALWAYS_USE_QSORT 
EXTRAS   := -DLOWHAT_QSORT_THRESHOLD=256 -DLOWHAT_MMMALLOC_CTRS -DLOWHAT_COUNTERS  
CFLAGS   :=  -g -Wall -Werror ${OPT} -I../include ${EXTRAS}
PROGNAME := test

all: ${PROGNAME} Makefile

# DO NOT MANUALLY EDIT OR REMOVE ANYTHING BELOW THIS LINE.
# SOURCE DEPENDENCIES ARE COMPUTED BY dep.py
# begin autogenerated content
SRCFILES := lowhat1.c lowhat2.c lowhat0.c hihat1.c refhat0.c mmm.c counters.c testhat.c test.c xxhash.c
OBJFILES := ${SRCFILES:c=o}
lowhat1.o: lowhat1.c lowhat1.h lowhat_common.h mmm.h counters.h
lowhat2.o: lowhat2.c lowhat2.h lowhat_common.h mmm.h counters.h
lowhat0.o: lowhat0.c lowhat0.h lowhat_common.h mmm.h counters.h
hihat1.o: hihat1.c hihat1.h lowhat_common.h mmm.h counters.h
refhat0.o: refhat0.c refhat0.h lowhat_common.h mmm.h counters.h
mmm.o: mmm.c mmm.h counters.h
counters.o: counters.c counters.h
testhat.o: testhat.c testhat.h lowhat1.h lowhat2.h lowhat0.h lowhat_common.h mmm.h counters.h
test.o: test.c hash.h xxhash.h testhat.h lowhat1.h lowhat2.h lowhat0.h lowhat_common.h mmm.h counters.h
xxhash.o: xxhash.c xxhash.h
# end autogenerated content
test: ${OBJFILES} Makefile
	${CC} ${OBJFILES} -o ${PROGNAME}
%.o: %.c Makefile
	${CC} ${CFLAGS} -c $<
remake: clean ${PROGNAME}
clean:
	rm -f *.o *~ ../include/*~ ${PROGNAME}
dep:
	${ENV} python3 ../scripts/makedep.py
format:
	${ENV} clang-format -i [a-wyz]*.{c,h}
prep: format dep clean all
