#!/bin/sh


if [ ! -d scripts ]
then
    cd ..
    if [ ! -d scripts ]
       then 
         echo "Must be run from the scripts directory or the toplevel directory"
         exit
    fi
fi
./configure CFLAGS="-O0 -DHATRACK_MMM_DEBUG -DHATRACK_COUNTERS"
